use crate::circuit::{Circuit, ComponentType, NODE_GND, NODE_IN, NODE_OUT, NODE_VCC, NODE_VEE};
use crate::fitness::{to_characterization_netlist, BehaviorDescriptor};
use crate::spice::{run_simulation, AcPoint, SpiceError, TranPoint};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Duration;

#[derive(Debug)]
pub enum BenchError {
    Io(std::io::Error),
    Spice(SpiceError),
    MissingSimulationData(String),
}

impl std::fmt::Display for BenchError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BenchError::Io(e) => write!(f, "I/O error: {}", e),
            BenchError::Spice(e) => write!(f, "SPICE error: {}", e),
            BenchError::MissingSimulationData(s) => write!(f, "Missing simulation data: {}", s),
        }
    }
}

impl std::error::Error for BenchError {}

impl From<std::io::Error> for BenchError {
    fn from(err: std::io::Error) -> Self {
        BenchError::Io(err)
    }
}

impl From<SpiceError> for BenchError {
    fn from(err: SpiceError) -> Self {
        BenchError::Spice(err)
    }
}

#[derive(Debug, Clone)]
pub struct BenchPackageReport {
    pub output_dir: PathBuf,
    pub bom_path: PathBuf,
    pub protocol_path: PathBuf,
    pub reference_csv_path: PathBuf,
    pub reference_ac_path: PathBuf,
    pub netlist_path: PathBuf,
    pub component_count: usize,
    pub opamp_count: usize,
    pub diode_count: usize,
}

/// Generate Bill of Materials (BOM) & breadboard wiring guide
pub fn generate_bom(circuit: &Circuit, descriptor: &BehaviorDescriptor) -> String {
    let mut doc = String::new();

    doc.push_str("# 🛠️ Bill of Materials (BOM) & Breadboard Assembly Guide\n\n");
    doc.push_str("Generated by **İmbik Autonomous Analog Exploration Engine**.\n\n");

    // Behavior Summary
    doc.push_str("## 1. Behavior Overview\n");
    let is_filter = descriptor[0] > 0.5;
    let has_nonlinearity = descriptor[5] > 0.005 || descriptor[4] > 0.05 || descriptor[8] > 0.05;
    let is_oscillator = descriptor[9] > 0.05;

    let topology_type = if is_oscillator {
        "Autonomous Oscillator / Signal Generator"
    } else if is_filter && has_nonlinearity {
        "Non-linear Filtering & Wave-Shaping Stage"
    } else if is_filter {
        "Active Frequency Filter"
    } else if has_nonlinearity {
        "Non-linear Harmonic Distortion / Clipper Stage"
    } else {
        "Linear Buffer / Amplifier Stage"
    };

    doc.push_str(&format!("- **Topology Class**: {}\n", topology_type));
    doc.push_str(&format!("- **Total Components**: {}\n", circuit.components.len()));
    doc.push_str(&format!("- **Power Supply**: Dual Rails ±{:.1}V (VCC=+{:.1}V, VEE=-{:.1}V, GND=0V)\n", circuit.vcc, circuit.vcc, circuit.vee.abs()));
    if is_filter {
        let fc = 10f64.powf(descriptor[1] * 5.0);
        let slope = descriptor[2] * -40.0;
        doc.push_str(&format!("- **Predicted Cutoff Frequency ($f_c$)**: {:.1} Hz\n", fc));
        doc.push_str(&format!("- **Predicted Rolloff Slope**: {:.1} dB/decade\n", slope));
    }
    if has_nonlinearity {
        doc.push_str(&format!("- **Harmonics (2V drive)**: H2={:.4}, H3={:.4}, H5={:.4}\n", descriptor[5], descriptor[6], descriptor[7]));
        doc.push_str(&format!("- **Waveform Asymmetry Delta**: {:.4}\n", descriptor[4]));
        doc.push_str(&format!("- **Gain Compression**: {:.1}%\n", descriptor[8] * 100.0));
    }
    doc.push_str("\n---\n\n");

    // Group components by value and type
    let mut resistors: BTreeMap<String, usize> = BTreeMap::new();
    let mut capacitors: BTreeMap<String, usize> = BTreeMap::new();
    let mut diodes: BTreeMap<String, usize> = BTreeMap::new();
    let mut bjts: BTreeMap<String, usize> = BTreeMap::new();
    let mut opamps: usize = 0;

    for comp in &circuit.components {
        match comp.comp_type {
            ComponentType::R => *resistors.entry(comp.value.clone()).or_insert(0) += 1,
            ComponentType::C => *capacitors.entry(comp.value.clone()).or_insert(0) += 1,
            ComponentType::D => *diodes.entry(comp.value.clone()).or_insert(0) += 1,
            ComponentType::Q => *bjts.entry(comp.value.clone()).or_insert(0) += 1,
            ComponentType::X => opamps += 1,
            _ => {}
        }
    }

    doc.push_str("## 2. Component Checklist\n\n");
    doc.push_str("| Type | Part Name / Value | Quantity | Package | Notes |\n");
    doc.push_str("| :--- | :--- | :---: | :--- | :--- |\n");

    if opamps > 0 {
        let dip8_chips = opamps.div_ceil(2);
        doc.push_str(&format!(
            "| **IC** | **TL072** | {} chip(s) ({} op-amp section{}) | DIP-8 | Low-Noise Dual JFET Op-Amp |\n",
            dip8_chips,
            opamps,
            if opamps > 1 { "s" } else { "" }
        ));
    }

    for (val, count) in &bjts {
        let polarity = if val.contains("3906") { "PNP" } else { "NPN" };
        doc.push_str(&format!(
            "| **Transistor** | **{}** | {} | TO-92 | General Purpose {} BJT (Pin 1=E, 2=B, 3=C) |\n",
            val, count, polarity
        ));
    }

    for (val, count) in &diodes {
        doc.push_str(&format!(
            "| **Diode** | **{}** | {} | DO-35 (Axial) | Fast Switching Diode (Black Band = Cathode) |\n",
            val, count
        ));
    }

    for (val, count) in &resistors {
        doc.push_str(&format!(
            "| **Resistor** | **{}** | {} | 1/4W Through-Hole | 1% or 5% Metal/Carbon Film |\n",
            val, count
        ));
    }

    for (val, count) in &capacitors {
        doc.push_str(&format!(
            "| **Capacitor** | **{}** | {} | Radial / Ceramic / Film | ≥ 25V Rating |\n",
            val, count
        ));
    }

    doc.push_str("\n---\n\n");

    // Pinout & Polarity Guide
    doc.push_str("## 3. Pinout & Component Polarity Guide\n\n");
    doc.push_str("```text\n");
    if opamps > 0 {
        doc.push_str("         TL072 Dual Op-Amp (DIP-8 Package - Top View)\n");
        doc.push_str("                      ┌───∪───┐\n");
        doc.push_str("         (OUT1)  1 ───┤       ├─── 8  VCC (+9V)\n");
        doc.push_str("         (IN1-)  2 ───┤       ├─── 7  OUT2 (OUT2)\n");
        doc.push_str("         (IN1+)  3 ───┤       ├─── 6  IN2- (IN2-)\n");
        doc.push_str("      VEE (-9V)  4 ───┤       ├─── 5  IN2+ (IN2+)\n");
        doc.push_str("                      └───────┘\n\n");
    }
    if !bjts.is_empty() {
        doc.push_str("         2N3904 (NPN) / 2N3906 (PNP) BJT (TO-92 Package - Flat Face Front):\n");
        doc.push_str("                       ┌─────────┐\n");
        doc.push_str("                       │ 2N3904  │\n");
        doc.push_str("                       │ (Flat)  │\n");
        doc.push_str("                       └─┬──┬──┬─┘\n");
        doc.push_str("                         1  2  3\n");
        doc.push_str("                         │  │  │\n");
        doc.push_str("                         E  B  C  (1=Emitter, 2=Base, 3=Collector)\n\n");
    }
    if !diodes.is_empty() {
        doc.push_str("         1N4148 Diode Orientation:\n");
        doc.push_str("         [ Anode (+) ] ──────▶|────── [ Cathode (-) | Black Ring ]\n");
    }
    doc.push_str("```\n\n");

    if !opamps.is_multiple_of(2) {
        doc.push_str("> [!IMPORTANT]\n");
        doc.push_str("> **Unused Op-Amp Section Protection**: Circuit uses 1 section of a dual TL072 DIP-8.\n");
        doc.push_str("> To prevent erratic oscillation, tie unused section: **Pin 5 (IN2+) to GND**, and connect **Pin 6 (IN2-) to Pin 7 (OUT2)** directly.\n\n");
    }

    // Breadboard Node Netlist
    doc.push_str("## 4. Breadboard Node Connection Map\n\n");
    doc.push_str("| Node ID | Circuit Role | Wire Color | Connected Components & Pins |\n");
    doc.push_str("| :---: | :--- | :--- | :--- |\n");

    let mut node_map: BTreeMap<usize, Vec<String>> = BTreeMap::new();

    for comp in &circuit.components {
        let prefix = comp.comp_type.to_char();
        match comp.comp_type {
            ComponentType::R | ComponentType::C => {
                if comp.nodes.len() >= 2 {
                    node_map.entry(comp.nodes[0]).or_default().push(format!("{}{}[1] ({})", prefix, comp.id, comp.value));
                    node_map.entry(comp.nodes[1]).or_default().push(format!("{}{}[2] ({})", prefix, comp.id, comp.value));
                }
            }
            ComponentType::D => {
                if comp.nodes.len() >= 2 {
                    node_map.entry(comp.nodes[0]).or_default().push(format!("D{}[Anode]", comp.id));
                    node_map.entry(comp.nodes[1]).or_default().push(format!("D{}[Cathode | Band]", comp.id));
                }
            }
            ComponentType::Q => {
                if comp.nodes.len() >= 3 {
                    node_map.entry(comp.nodes[0]).or_default().push(format!("Q{}[Collector] ({})", comp.id, comp.value));
                    node_map.entry(comp.nodes[1]).or_default().push(format!("Q{}[Base] ({})", comp.id, comp.value));
                    node_map.entry(comp.nodes[2]).or_default().push(format!("Q{}[Emitter] ({})", comp.id, comp.value));
                }
            }
            ComponentType::X
                if comp.nodes.len() >= 5 => {
                    node_map.entry(comp.nodes[0]).or_default().push(format!("X{}[IN+]", comp.id));
                    node_map.entry(comp.nodes[1]).or_default().push(format!("X{}[IN-]", comp.id));
                    node_map.entry(comp.nodes[2]).or_default().push(format!("X{}[VCC Pin 8]", comp.id));
                    node_map.entry(comp.nodes[3]).or_default().push(format!("X{}[VEE Pin 4]", comp.id));
                    node_map.entry(comp.nodes[4]).or_default().push(format!("X{}[OUT Pin 1]", comp.id));
                }
            _ => {}
        }
    }

    for (node, pins) in &node_map {
        let (role, color) = match *node {
            NODE_GND => ("System Ground (0V)", "Black"),
            NODE_IN => ("Audio Signal INPUT", "Yellow"),
            NODE_OUT => ("Processed Signal OUTPUT", "Green / White"),
            NODE_VCC => ("Positive Supply (+9V)", "Red"),
            NODE_VEE => ("Negative Supply (-9V)", "Blue"),
            _ => ("Internal Tie Point", "Orange / Violet"),
        };

        doc.push_str(&format!(
            "| **Node {}** | {} | **{}** | {} |\n",
            node,
            role,
            color,
            pins.join(", ")
        ));
    }

    doc
}

/// Generate step-by-step physical bench measurement and calibration protocol
pub fn generate_protocol(circuit: &Circuit, descriptor: &BehaviorDescriptor) -> String {
    let mut doc = String::new();

    doc.push_str("# 📋 Physical Breadboard Test & Measurement Protocol\n\n");
    doc.push_str("Follow these sequential verification steps before connecting sensitive audio interfaces or amplifiers.\n\n");

    // Bench Setup
    doc.push_str("## 1. Required Bench Equipment\n");
    doc.push_str("1. **Dual DC Power Supply** (or two series 9V batteries with center-tap GND).\n");
    doc.push_str("2. **Digital Multimeter (DMM)** for continuity and DC operating point verification.\n");
    doc.push_str("3. **Function / Arbitrary Waveform Generator** (capable of 100mVpp to 5Vpp sine wave at 1kHz).\n");
    doc.push_str("4. **Dual-Channel Oscilloscope** with 10X probes (Ch1: Input, Ch2: Output).\n\n");
    doc.push_str("---\n\n");

    // Step 1
    doc.push_str("## Step 1: Pre-Power Cold Resistance & Short-Circuit Inspection\n");
    doc.push_str("> [!CAUTION]\n");
    doc.push_str("> **DO NOT apply DC power** until completing this inspection!\n\n");
    doc.push_str("1. Disconnect all external power sources.\n");
    doc.push_str("2. Set DMM to Resistance / Continuity mode.\n");
    doc.push_str("3. Measure resistance across rails:\n");
    doc.push_str("   - **VCC (Node 3) to GND (Node 0)**: Must be `> 10 kΩ` (No short).\n");
    doc.push_str("   - **VEE (Node 4) to GND (Node 0)**: Must be `> 10 kΩ` (No short).\n");
    doc.push_str("   - **VCC (Node 3) to VEE (Node 4)**: Must be `> 20 kΩ` (No short).\n");

    let has_bjts = circuit.components.iter().any(|c| c.comp_type == ComponentType::Q);
    let has_opamps = circuit.components.iter().any(|c| c.comp_type == ComponentType::X);
    let has_diodes = circuit.components.iter().any(|c| c.comp_type == ComponentType::D);

    let mut step_num = 4;
    if has_bjts {
        doc.push_str(&format!("{}. Inspect BJT transistor pinout (2N3904 / 2N3906 TO-92: E-B-C looking at flat front with leads pointing down): Ensure Collector, Base, and Emitter match schematic connections.\n", step_num));
        step_num += 1;
    }
    if has_opamps {
        doc.push_str(&format!("{}. Inspect TL072 op-amp orientation: Pin 1 notch/dot must align with your breadboard layout.\n", step_num));
        step_num += 1;
    }
    if has_diodes {
        doc.push_str(&format!("{}. Inspect 1N4148 diodes: Ensure the black cathode stripe matches the BOM diagram.\n", step_num));
    }
    doc.push('\n');

    // Step 2
    doc.push_str("## Step 2: DC Power-On & Quiescent Bias Verification\n");
    doc.push_str(&format!("1. Turn on the dual supply (+{:.1}V and -{:.1}V).\n", circuit.vcc, circuit.vee.abs()));
    let normal_current = if has_opamps {
        "2.5 mA to 5.0 mA per TL072 package"
    } else if has_bjts {
        "1.0 mA to 10.0 mA depending on bias divider resistors"
    } else {
        "< 5.0 mA"
    };
    doc.push_str(&format!("2. Observe total supply current: Normal quiescent current is **{}**. If current exceeds 25mA, shut off immediately and check wiring for shorts!\n", normal_current));
    doc.push_str("3. Set DMM to DC Volts mode. Ground the black lead to Node 0 (GND).\n");
    doc.push_str("4. Measure DC voltages at key nodes:\n");
    doc.push_str(&format!("   - **Node 3 (VCC)**: `+{:.1}V ± 0.3V`\n", circuit.vcc));
    doc.push_str(&format!("   - **Node 4 (VEE)**: `-{:.1}V ± 0.3V`\n", circuit.vee.abs()));
    doc.push_str("   - **Node 2 (OUT)**: Must be between `-1.5V` and `+1.5V` (expected near 0.0V DC).\n");
    if has_opamps {
        doc.push_str("   - *If Node 2 is pinned to rails (±7.5V), the op-amp is saturated. Check feedback network and inverting input wiring.*\n\n");
    } else if has_bjts {
        doc.push_str("   - *If Node 2 is pinned to rails, the BJT is in saturation or cutoff. Verify base bias divider resistors and emitter pull-down/pull-up.*\n\n");
    } else {
        doc.push_str("   - *If Node 2 is pinned to rails, verify rail connections and load termination.*\n\n");
    }

    // Step 3
    doc.push_str("## Step 3: Small-Signal Linear Response (100mV peak / 200mVpp, 1kHz)\n");
    doc.push_str("1. Connect Function Generator to **Node 1 (IN)** and **Node 0 (GND)**.\n");
    doc.push_str("2. Set waveform: **1000 Hz Sine Wave**, amplitude **200 mV peak-to-peak** (100 mV peak), 0.0V DC offset.\n");
    doc.push_str("3. Connect Oscilloscope:\n");
    doc.push_str("   - **Ch1 (Yellow)**: Probe Node 1 (IN).\n");
    doc.push_str("   - **Ch2 (Blue/Green)**: Probe Node 2 (OUT).\n");
    doc.push_str("4. Measure Ch2 peak-to-peak voltage.\n");
    doc.push_str("5. Note linear gain: $G = V_{out,pp} / 200\\text{mV}$. Verify waveform is a clean, undistorted sine wave.\n\n");

    // Step 4
    doc.push_str("## Step 4: Large-Signal Non-linear Characterization (2.0V peak / 4.0Vpp, 1kHz)\n");
    let has_nonlinearity = descriptor[5] > 0.005 || descriptor[4] > 0.05 || descriptor[8] > 0.05;
    if has_nonlinearity {
        doc.push_str("This circuit exhibits non-linear wave-shaping character!\n\n");
    }
    doc.push_str("1. Increase generator amplitude to **4.0 V peak-to-peak** (2.0 V peak), 1kHz sine.\n");
    doc.push_str("2. Observe Ch2 output waveform on the oscilloscope:\n");
    doc.push_str(&format!("   - **Predicted Asymmetry Index**: {:.3} (Look for positive vs negative peak clipping differences).\n", descriptor[4]));
    doc.push_str(&format!("   - **Predicted Harmonics Ratio**: H2={:.3}, H3={:.3}, H5={:.3}\n", descriptor[5], descriptor[6], descriptor[7]));
    doc.push_str(&format!("   - **Predicted Dynamic Compression**: {:.1}%\n", descriptor[8] * 100.0));
    doc.push_str("3. Check for diode knee conduction around ±0.6V or soft op-amp saturation shoulders.\n\n");

    // Step 5
    if descriptor[0] > 0.5 {
        let fc = 10f64.powf(descriptor[1] * 5.0);
        doc.push_str("## Step 5: Frequency Response & Cutoff Verification\n");
        doc.push_str(&format!("This circuit is configured as an active filter with expected cutoff near **{:.0} Hz**.\n\n", fc));
        doc.push_str("1. Set generator amplitude to **1.0 Vpp**.\n");
        doc.push_str("2. Sweep generator frequency from 100 Hz up to 20 kHz.\n");
        doc.push_str(&format!("3. Locate the -3dB frequency ($V_{{out}} = 0.707 \\times V_{{passband}}$): Compare with simulated {:.0} Hz.\n", fc));
        doc.push_str("4. Verify roll-off slope in the attenuation band.\n\n");
    }

    // Step 6
    if descriptor[9] > 0.05 {
        doc.push_str("## Step 6: Autonomous Oscillation Check\n");
        doc.push_str("This circuit contains autonomous oscillatory dynamics!\n\n");
        doc.push_str("1. Disconnect the function generator from Node 1 (or terminate Node 1 to GND with a 50Ω resistor).\n");
        doc.push_str("2. Trigger the oscilloscope on Ch2 with 50mV/div sensitivity.\n");
        doc.push_str(&format!("3. Measure the natural self-oscillation frequency (expected ~{:.1} kHz).\n\n", 10f64.powf(descriptor[10] * 5.0) / 1000.0));
    }

    // Step 7
    doc.push_str("## Step 7: Oscilloscope Data Export for Ingest (Stage 9)\n");
    doc.push_str("1. With 1kHz 4Vpp input connected, press **Single / Stop** on your oscilloscope.\n");
    doc.push_str("2. Export the waveform to a USB flash drive as CSV format.\n");
    doc.push_str("3. Save the file as `scope_capture.csv`.\n");
    doc.push_str("4. Run `imbik ingest scope_capture.csv` to overlay physical reality against SPICE simulation curves!\n");

    doc
}

/// Generate uniform time-domain reference CSV (3ms to 5ms, 2 full cycles at 1kHz)
pub fn generate_reference_csv(
    tran_small: &[TranPoint],
    tran_large: &[TranPoint],
) -> Result<String, BenchError> {
    if tran_small.is_empty() || tran_large.is_empty() {
        return Err(BenchError::MissingSimulationData("Transient points empty".to_string()));
    }

    let mut csv = String::new();
    csv.push_str("time_s,v_in_small_v,v_out_small_v,v_in_large_v,v_out_large_v\n");

    let num_samples = 256;
    let t_start = 0.003; // Steady state 3ms
    let t_end = 0.005;   // 5ms (2 full cycles of 1kHz)
    let dt = (t_end - t_start) / (num_samples as f64);

    for i in 0..=num_samples {
        let t = t_start + (i as f64) * dt;
        let v_out_s = crate::fitness::interpolate_tran(tran_small, t);
        let v_in_s = crate::fitness::interpolate_tran_in(tran_small, t);
        let v_out_l = crate::fitness::interpolate_tran(tran_large, t);
        let v_in_l = crate::fitness::interpolate_tran_in(tran_large, t);

        csv.push_str(&format!(
            "{:.6e},{:.6e},{:.6e},{:.6e},{:.6e}\n",
            t, v_in_s, v_out_s, v_in_l, v_out_l
        ));
    }

    Ok(csv)
}

/// Generate AC frequency sweep reference CSV (10Hz to 100kHz)
pub fn generate_reference_ac_csv(ac_points: &[AcPoint]) -> Result<String, BenchError> {
    if ac_points.is_empty() {
        return Err(BenchError::MissingSimulationData("AC points empty".to_string()));
    }

    let mut csv = String::new();
    csv.push_str("freq_hz,mag_db,phase_deg\n");

    for pt in ac_points {
        csv.push_str(&format!("{:.4e},{:.4e},{:.4e}\n", pt.freq, pt.mag_db, pt.phase_deg));
    }

    Ok(csv)
}

/// Export full breadboard bench package to a dedicated directory
pub fn generate_bench_package(
    circuit: &Circuit,
    descriptor: &BehaviorDescriptor,
    output_dir: &Path,
    timeout: Duration,
) -> Result<BenchPackageReport, BenchError> {
    fs::create_dir_all(output_dir)?;

    // 1. Generate BOM
    let bom_content = generate_bom(circuit, descriptor);
    let bom_path = output_dir.join("bom.md");
    fs::write(&bom_path, bom_content)?;

    // 2. Generate Protocol
    let protocol_content = generate_protocol(circuit, descriptor);
    let protocol_path = output_dir.join("protocol.md");
    fs::write(&protocol_path, protocol_content)?;

    // 3. Generate SPICE Simulation Curves
    let netlist = to_characterization_netlist(circuit, "Bench Ref", 22.0);
    let netlist_path = output_dir.join("circuit.net");
    fs::write(&netlist_path, &netlist)?;

    let sim_res = run_simulation(&netlist, timeout)?;

    let tran_s = sim_res.tran_small.ok_or_else(|| {
        BenchError::MissingSimulationData("Missing small-signal tran".to_string())
    })?;
    let tran_l = sim_res.tran_large.ok_or_else(|| {
        BenchError::MissingSimulationData("Missing large-signal tran".to_string())
    })?;
    let ac_data = sim_res.ac_response.ok_or_else(|| {
        BenchError::MissingSimulationData("Missing AC response".to_string())
    })?;

    let ref_csv = generate_reference_csv(&tran_s, &tran_l)?;
    let ref_csv_path = output_dir.join("reference.csv");
    fs::write(&ref_csv_path, ref_csv)?;

    let ref_ac_csv = generate_reference_ac_csv(&ac_data)?;
    let ref_ac_path = output_dir.join("reference_ac.csv");
    fs::write(&ref_ac_path, ref_ac_csv)?;

    let opamp_count = circuit
        .components
        .iter()
        .filter(|c| c.comp_type == ComponentType::X)
        .count();
    let diode_count = circuit
        .components
        .iter()
        .filter(|c| c.comp_type == ComponentType::D)
        .count();

    Ok(BenchPackageReport {
        output_dir: output_dir.to_path_buf(),
        bom_path,
        protocol_path,
        reference_csv_path: ref_csv_path,
        reference_ac_path: ref_ac_path,
        netlist_path,
        component_count: circuit.components.len(),
        opamp_count,
        diode_count,
    })
}

/// Ingest analysis report comparing physical oscilloscope CSV against SPICE reference
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestResult {
    pub num_samples: usize,
    pub pearson_r: f64,
    pub nrmse: f64,
    pub is_verified: bool,
    pub details: String,
}

/// Ingest physical oscilloscope capture CSV and compare against SPICE reference.
/// Supports standard oscilloscope CSV formats (time, ch1_in, ch2_out or time, ch2_out).
pub fn ingest_scope_data(
    scope_csv_path: &Path,
    ref_csv_path: &Path,
) -> Result<IngestResult, BenchError> {
    let scope_content = fs::read_to_string(scope_csv_path)
        .map_err(|e| BenchError::MissingSimulationData(format!("Could not read scope capture file: {}", e)))?;
    let ref_content = fs::read_to_string(ref_csv_path)
        .map_err(|e| BenchError::MissingSimulationData(format!("Could not read reference CSV: {}", e)))?;

    // Parse reference large-signal output points (time, v_out_large)
    let mut ref_times = Vec::new();
    let mut ref_vouts = Vec::new();
    for line in ref_content.lines().skip(1) {
        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() >= 5
            && let (Ok(t), Ok(v)) = (parts[0].parse::<f64>(), parts[4].parse::<f64>()) {
                ref_times.push(t);
                ref_vouts.push(v);
            }
    }

    if ref_times.is_empty() {
        return Err(BenchError::MissingSimulationData("Reference CSV has no valid data points".to_string()));
    }

    // Parse scope data
    let mut scope_vouts = Vec::new();
    let mut scope_times = Vec::new();
    for line in scope_content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("time") || trimmed.starts_with("Time") || trimmed.starts_with('x') || trimmed.starts_with('X') {
            continue;
        }
        let parts: Vec<&str> = trimmed.split([',', '\t', ' ']).filter(|s| !s.is_empty()).collect();
        if parts.len() >= 2
            && let (Ok(t), Ok(v)) = (parts[0].parse::<f64>(), parts[parts.len() - 1].parse::<f64>()) {
                scope_times.push(t);
                scope_vouts.push(v);
            }
    }

    if scope_vouts.len() < 10 {
        return Err(BenchError::MissingSimulationData(format!(
            "Scope capture CSV has insufficient valid sample rows (got {}, need >= 10)",
            scope_vouts.len()
        )));
    }

    // Resample / interpolate reference onto scope time grid or compare normalized peaks
    let n = scope_vouts.len();
    let mean_scope: f64 = scope_vouts.iter().sum::<f64>() / (n as f64);
    let min_scope = scope_vouts.iter().copied().fold(f64::INFINITY, f64::min);
    let max_scope = scope_vouts.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let span_scope = (max_scope - min_scope).max(1e-6);

    let min_ref = ref_vouts.iter().copied().fold(f64::INFINITY, f64::min);
    let max_ref = ref_vouts.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let span_ref = (max_ref - min_ref).max(1e-6);

    // Compute Pearson correlation across resampled matching cycles
    let mut s_scope = 0.0;
    let mut s_ref = 0.0;
    let mut s_prod = 0.0;
    let mut sq_diff_sum = 0.0;

    let eval_samples = 128;
    for i in 0..eval_samples {
        let frac = (i as f64) / (eval_samples as f64);
        let idx_s = ((frac * (scope_vouts.len() as f64)) as usize).min(scope_vouts.len() - 1);
        let idx_r = ((frac * (ref_vouts.len() as f64)) as usize).min(ref_vouts.len() - 1);

        let norm_s = (scope_vouts[idx_s] - mean_scope) / span_scope;
        let norm_r = (ref_vouts[idx_r] - (min_ref + span_ref / 2.0)) / span_ref;

        s_scope += norm_s * norm_s;
        s_ref += norm_r * norm_r;
        s_prod += norm_s * norm_r;

        let diff = norm_s - norm_r;
        sq_diff_sum += diff * diff;
    }

    let pearson_r = if s_scope > 1e-9 && s_ref > 1e-9 {
        (s_prod / (s_scope.sqrt() * s_ref.sqrt())).clamp(-1.0, 1.0)
    } else {
        0.0
    };

    let nrmse = (sq_diff_sum / (eval_samples as f64)).sqrt();
    let is_verified = pearson_r >= 0.85 && nrmse <= 0.35;

    let details = format!(
        "Ingest Analysis: Pearson r = {:.4}, NRMSE = {:.4}, Samples = {}. Status: {}",
        pearson_r, nrmse, scope_vouts.len(),
        if is_verified { "HARDWARE VERIFIED (LEGENDARY MATCH)" } else { "DEVIATION DETECTED" }
    );

    Ok(IngestResult {
        num_samples: scope_vouts.len(),
        pearson_r,
        nrmse,
        is_verified,
        details,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::circuit::{Circuit, Component, NODE_GND, NODE_IN, NODE_OUT, NODE_VCC, NODE_VEE};
    use crate::fitness::extract_behavior_descriptor;

    fn build_test_diode_clipper() -> Circuit {
        let mut c = Circuit::new();
        c.add_component(Component::new('R', 1, vec![NODE_IN, 10], "1k").unwrap());
        c.add_component(Component::new('D', 1, vec![10, NODE_GND], "1N4148").unwrap());
        c.add_component(
            Component::new('X', 1, vec![10, NODE_OUT, NODE_VCC, NODE_VEE, NODE_OUT], "TL072").unwrap(),
        );
        c.validate().unwrap();
        c
    }

    #[test]
    fn test_generate_bench_package_creates_all_artifacts() {
        let circuit = build_test_diode_clipper();
        let timeout = Duration::from_secs(3);
        let desc = extract_behavior_descriptor(&circuit, 22.0, timeout).expect("Desc failed");

        let bench_dir = PathBuf::from("target/test_bench_package/clipper_01");
        let _ = fs::remove_dir_all(&bench_dir);

        let report = generate_bench_package(&circuit, &desc, &bench_dir, timeout)
            .expect("Failed to generate bench package");

        // 1. Verify files exist on disk
        assert!(report.bom_path.exists(), "bom.md must exist");
        assert!(report.protocol_path.exists(), "protocol.md must exist");
        assert!(report.reference_csv_path.exists(), "reference.csv must exist");
        assert!(report.reference_ac_path.exists(), "reference_ac.csv must exist");
        assert!(report.netlist_path.exists(), "circuit.net must exist");

        // 2. Verify BOM content
        let bom = fs::read_to_string(&report.bom_path).unwrap();
        assert!(bom.contains("TL072"), "BOM must mention TL072");
        assert!(bom.contains("1N4148"), "BOM must mention 1N4148");
        assert!(bom.contains("1k"), "BOM must mention 1k resistor");
        assert!(bom.contains("DIP-8"), "BOM must include DIP-8 pinout");

        // 3. Verify Protocol content
        let protocol = fs::read_to_string(&report.protocol_path).unwrap();
        assert!(protocol.contains("Pre-Power Cold Resistance"), "Must include Step 1");
        assert!(protocol.contains("Small-Signal Linear Response"), "Must include Step 3");
        assert!(protocol.contains("Large-Signal Non-linear Characterization"), "Must include Step 4");

        // 4. Verify CSV content & line count
        let csv = fs::read_to_string(&report.reference_csv_path).unwrap();
        let lines: Vec<&str> = csv.lines().collect();
        assert!(lines.len() >= 250, "reference.csv must have >= 250 points, got {}", lines.len());
        assert!(lines[0].contains("time_s,v_in_small_v,v_out_small_v"), "CSV header must match");

        let ac_csv = fs::read_to_string(&report.reference_ac_path).unwrap();
        let ac_lines: Vec<&str> = ac_csv.lines().collect();
        assert!(ac_lines.len() >= 50, "reference_ac.csv must have >= 50 points, got {}", ac_lines.len());

        println!("Bench Package test passed! Directory: {:?}", report.output_dir);
    }

    #[test]
    fn test_ingest_scope_data_validation() {
        let temp_dir = tempfile::Builder::new().prefix("imbik_test_ingest_").tempdir().unwrap();
        let ref_csv_path = temp_dir.path().join("reference.csv");
        let scope_csv_path = temp_dir.path().join("scope_capture.csv");

        // Write synthetic reference CSV
        let mut ref_content = String::from("time_s,v_in_small_v,v_out_small_v,v_in_large_v,v_out_large_v\n");
        for i in 0..100 {
            let t = 0.003 + (i as f64) * 0.00002;
            let v_out = 1.5 * (2.0 * std::f64::consts::PI * 1000.0 * t).sin();
            ref_content.push_str(&format!("{:.6e},0.0,0.0,0.0,{:.6e}\n", t, v_out));
        }
        fs::write(&ref_csv_path, ref_content).unwrap();

        // Write matching synthetic oscilloscope CSV (with minor 2% noise)
        let mut scope_content = String::from("Time,Channel2\n");
        for i in 0..100 {
            let t = 0.003 + (i as f64) * 0.00002;
            let v_out = 1.48 * (2.0 * std::f64::consts::PI * 1000.0 * t).sin() + 0.01;
            scope_content.push_str(&format!("{:.6e},{:.6e}\n", t, v_out));
        }
        fs::write(&scope_csv_path, scope_content).unwrap();

        let ingest_res = ingest_scope_data(&scope_csv_path, &ref_csv_path).expect("Ingest analysis failed");
        println!("Ingest result: {:?}", ingest_res);

        assert!(ingest_res.is_verified, "Matching scope capture must verify as hardware-confirmed");
        assert!(ingest_res.pearson_r > 0.95, "Pearson r should be > 0.95, got {:.4}", ingest_res.pearson_r);
        assert!(ingest_res.nrmse < 0.15, "NRMSE should be low, got {:.4}", ingest_res.nrmse);
    }
}
